### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by DeepDiver1975** [cernbox/reva#5]
Web clients (like phoenix) want to talk to ocdavsvc using cross domain requests.

Therefore CORS support shall be added to reva/ocdavsvc

https://github.com/cernbox/reva/tree/a6be57bfedc01eddf38148bb7015c2fb8a7a0058/services/httpsvc/ocdavsvc

**Comment by labkode** [comment]
Closed by #24 

See revad.toml.

Options are defined here: 
https://github.com/rs/cors#parameters

With the following naming convention:
AllowedHeaders => allowed_headers
